
working_directory = "None"

[window]
decorations = "buttonless"
opacity = 1
title = "Alacritty"
dynamic_title = true

  [window.padding]
  x = 3
  y = 5

[font]
size = 14

  [font.normal]
  family = "Cousine Nerd Font Mono"

[color_schemes.latte.primary]
background = "#EFF1F5"
foreground = "#4C4F69"
dim_foreground = "#4C4F69"
bright_foreground = "#4C4F69"

[color_schemes.latte.cursor]
text = "#EFF1F5"
cursor = "#DC8A78"

[color_schemes.latte.vi_mode_cursor]
text = "#EFF1F5"
cursor = "#7287FD"

[color_schemes.latte.search.matches]
foreground = "#EFF1F5"
background = "#6C6F85"

[color_schemes.latte.search.focused_match]
foreground = "#EFF1F5"
background = "#40A02B"

[color_schemes.latte.search.footer_bar]
foreground = "#EFF1F5"
background = "#6C6F85"

[color_schemes.latte.hints.start]
foreground = "#EFF1F5"
background = "#DF8E1D"

[color_schemes.latte.hints.end]
foreground = "#EFF1F5"
background = "#6C6F85"

[color_schemes.latte.selection]
text = "#EFF1F5"
background = "#DC8A78"

[color_schemes.latte.normal]
black = "#5C5F77"
red = "#D20F39"
green = "#40A02B"
yellow = "#DF8E1D"
blue = "#1E66F5"
magenta = "#EA76CB"
cyan = "#179299"
white = "#ACB0BE"

[color_schemes.latte.bright]
black = "#6C6F85"
red = "#D20F39"
green = "#40A02B"
yellow = "#DF8E1D"
blue = "#1E66F5"
magenta = "#EA76CB"
cyan = "#179299"
white = "#BCC0CC"

[color_schemes.latte.dim]
black = "#5C5F77"
red = "#D20F39"
green = "#40A02B"
yellow = "#DF8E1D"
blue = "#1E66F5"
magenta = "#EA76CB"
cyan = "#179299"
white = "#ACB0BE"

[[color_schemes.latte.indexed_colors]]
index = 16
color = "#FE640B"

[[color_schemes.latte.indexed_colors]]
index = 17
color = "#DC8A78"

[color_schemes.frappe.primary]
background = "#303446"
foreground = "#C6D0F5"
dim_foreground = "#C6D0F5"
bright_foreground = "#C6D0F5"

[color_schemes.frappe.cursor]
text = "#303446"
cursor = "#F2D5CF"

[color_schemes.frappe.vi_mode_cursor]
text = "#303446"
cursor = "#BABBF1"

[color_schemes.frappe.search.matches]
foreground = "#303446"
background = "#A5ADCE"

[color_schemes.frappe.search.focused_match]
foreground = "#303446"
background = "#A6D189"

[color_schemes.frappe.search.footer_bar]
foreground = "#303446"
background = "#A5ADCE"

[color_schemes.frappe.hints.start]
foreground = "#303446"
background = "#E5C890"

[color_schemes.frappe.hints.end]
foreground = "#303446"
background = "#A5ADCE"

[color_schemes.frappe.selection]
text = "#303446"
background = "#F2D5CF"

[color_schemes.frappe.normal]
black = "#51576D"
red = "#E78284"
green = "#A6D189"
yellow = "#E5C890"
blue = "#8CAAEE"
magenta = "#F4B8E4"
cyan = "#81C8BE"
white = "#B5BFE2"

[color_schemes.frappe.bright]
black = "#626880"
red = "#E78284"
green = "#A6D189"
yellow = "#E5C890"
blue = "#8CAAEE"
magenta = "#F4B8E4"
cyan = "#81C8BE"
white = "#A5ADCE"

[color_schemes.frappe.dim]
black = "#51576D"
red = "#E78284"
green = "#A6D189"
yellow = "#E5C890"
blue = "#8CAAEE"
magenta = "#F4B8E4"
cyan = "#81C8BE"
white = "#B5BFE2"

[[color_schemes.frappe.indexed_colors]]
index = 16
color = "#EF9F76"

[[color_schemes.frappe.indexed_colors]]
index = 17
color = "#F2D5CF"

[color_schemes.macchiato.primary]
background = "#000000"
foreground = "#CAD3F5"
dim_foreground = "#CAD3F5"
bright_foreground = "#CAD3F5"

[color_schemes.macchiato.cursor]
text = "#000000"
cursor = "#F4DBD6"

[color_schemes.macchiato.vi_mode_cursor]
text = "#000000"
cursor = "#B7BDF8"

[color_schemes.macchiato.search.matches]
foreground = "#000000"
background = "#A5ADCB"

[color_schemes.macchiato.search.focused_match]
foreground = "#000000"
background = "#A6DA95"

[color_schemes.macchiato.search.footer_bar]
foreground = "#000000"
background = "#A5ADCB"

[color_schemes.macchiato.hints.start]
foreground = "#000000"
background = "#EED49F"

[color_schemes.macchiato.hints.end]
foreground = "#000000"
background = "#A5ADCB"

[color_schemes.macchiato.selection]
text = "#000000"
background = "#F4DBD6"

[color_schemes.macchiato.normal]
black = "#494D64"
red = "#ED8796"
green = "#A6DA95"
yellow = "#EED49F"
blue = "#8AADF4"
magenta = "#F5BDE6"
cyan = "#8BD5CA"
white = "#B8C0E0"

[color_schemes.macchiato.bright]
black = "#5B6078"
red = "#ED8796"
green = "#A6DA95"
yellow = "#EED49F"
blue = "#8AADF4"
magenta = "#F5BDE6"
cyan = "#8BD5CA"
white = "#A5ADCB"

[color_schemes.macchiato.dim]
black = "#494D64"
red = "#ED8796"
green = "#A6DA95"
yellow = "#EED49F"
blue = "#8AADF4"
magenta = "#F5BDE6"
cyan = "#8BD5CA"
white = "#B8C0E0"

[[color_schemes.macchiato.indexed_colors]]
index = 16
color = "#F5A97F"

[[color_schemes.macchiato.indexed_colors]]
index = 17
color = "#F4DBD6"

[color_schemes.mocha.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[color_schemes.mocha.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[color_schemes.mocha.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[color_schemes.mocha.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[color_schemes.mocha.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[color_schemes.mocha.search.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"

[color_schemes.mocha.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[color_schemes.mocha.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[color_schemes.mocha.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[color_schemes.mocha.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[color_schemes.mocha.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"

[color_schemes.mocha.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[[color_schemes.mocha.indexed_colors]]
index = 16
color = "#FAB387"

[[color_schemes.mocha.indexed_colors]]
index = 17
color = "#F5E0DC"

[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.search.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"

[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"

[cursor.style]
shape = "Block"
blinking = "Off"

[mouse]
hide_when_typing = false

[[key_bindings]]
key = "Q"
mods = "Command"
action = "Quit"

[[key_bindings]]
key = "W"
mods = "Command"
action = "Quit"

[[key_bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"
